# bundle exec jekyll serve --host=0.0.0.0

title: MycilaMQTT
description: A simple and efficient MQTT helper for Arduino / ESP32 based on Espressif MQTT Client
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
